github.com:
    users:
        kimjindol2025:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: kimjindol2025
