github.com:
    users:
        kimjindol2025:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: kimjindol2025
