{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
    environment: {{ .Values.global.environment }}
{{- end }}
