{{- if .Values.persistence.enabled }}
---
# PersistentVolumeClaim for Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "distributed-bank.fullname" . }}-data
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "distributed-bank.labels" . | nindent 4 }}
    component: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
